### ISSUE TITLE
ode-toolbox globally redirects stderr to /dev/null

### ISSUE THREAD

**Issue by clinssen** [nest/ode-toolbox#13]
ode-toolbox globally redirects stderr to /dev/null:

https://github.com/nest/ode-toolbox/blob/404b6651e69e08efd146eea7e35f805b59ccde15/odetoolbox/stiffness.py#L36

This is a problem when another Python package imports odetoolbox but still wants to use stderr for error reporting (I encountered this bug because antlr4's parse errors during NESTML parsing were not being printed to console).

**Comment by jougs** [comment]
This (among many other things) is solved in #12. Can you please review that and check in how far the invocation in NESTML needs to change to use the obhect-oriented interface #12 brings? Many thanks!
